### ISSUE TITLE
rails 4 Capistrano 3.1, seeds not populated

### ISSUE THREAD

**Issue by tsyber1an** [dei79/capistrano-rails-collection#6]
Hey, 

i have my custom staging env and when i typed

`cap staging rails:rake:db:seed`

no data seeds to db.

Do i missing something for run options?

**Comment by zonkeynir** [comment]
Well, yes . 
The the environment is executing the script on the stage and not RAILS_ENV
as u see here 
      desc "Load the seed data from db/seeds.rb"
      task :seed do
        on primary :db do
          within release_path do
            with rails_env: fetch(:stage) do
              execute :rake, 'db:seed'
            end
          end
        end
      end



I suggest a pull with a fix to fetch RAILS_ENV instead of stage

**Comment by Funfun** [comment]
Cool, thanks!
